import { ArtWork } from './../models/art-work.model';
import { Category } from './../models/category.model';

export class LJData{
	public categories: Array<Category> = [];
	public retailArtWorks: Array<ArtWork> = [];
	public threeDArtWorks: Array<ArtWork> = [];
	public paintingArtWorks: Array<ArtWork> = [];

	constructor(){		
	   this.initRetailArtWorks();
	   this.initThreeDArtWorks();
	   this.initPaintingArtWorks();
	}

	initPaintingArtWorks(){
		this.paintingArtWorks = [
			new ArtWork("",
			"images/projects/paintings/1_b.jpg",
			["images/projects/paintings/original/1_b.jpg"]),
			new ArtWork("",
			"images/projects/paintings/2_b.jpg",
			["images/projects/paintings/original/2_b.jpg"]),
			new ArtWork("",
			"images/projects/paintings/3_b.jpg",
			["images/projects/paintings/original/3_b.jpg"]),
			new ArtWork("",
			"images/projects/paintings/4_b.jpg",
			["images/projects/paintings/original/4_b.jpg"]),
			new ArtWork("",
			"images/projects/paintings/5_b.jpg",
			["images/projects/paintings/original/5_b.jpg"])
		]
		this.categories.push(new Category("Paintings", this.paintingArtWorks));
	}

	initThreeDArtWorks(){
		this.threeDArtWorks = [
			new ArtWork("",
			"images/projects/3d perspectives/Bar.jpg",
			["images/projects/3d perspectives/original/Bar.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/bathroom (Small).jpg",
			["images/projects/3d perspectives/original/bathroom (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Bedroom (Small).jpg",
			["images/projects/3d perspectives/original/Bedroom (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big (Small).jpg",
			["images/projects/3d perspectives/original/big (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big01 (Small).jpg",
			["images/projects/3d perspectives/original/big01 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big01.jpg",
			["images/projects/3d perspectives/original/big01.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big02.jpg",
			["images/projects/3d perspectives/original/big02.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big03 (Small).jpg",
			["images/projects/3d perspectives/original/big03 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big04 (Small).jpg",
			["images/projects/3d perspectives/original/big04 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big05.jpg",
			["images/projects/3d perspectives/original/big05.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/big06.jpg",
			["images/projects/3d perspectives/original/big06.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/box-big.jpg",
			["images/projects/3d perspectives/original/box-big.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Delong.jpg",
			["images/projects/3d perspectives/original/Delong.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Ensite.jpg",
			["images/projects/3d perspectives/original/Ensite.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Ensite2.jpg",
			["images/projects/3d perspectives/original/Ensite2.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Fancy.jpg",
			["images/projects/3d perspectives/original/Fancy.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Ford-Boardroom.jpg",
			["images/projects/3d perspectives/original/Ford-Boardroom.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Geberit.jpg",
			["images/projects/3d perspectives/original/Geberit.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/image2-big (Small).jpg",
			["images/projects/3d perspectives/original/image2-big (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Japan.jpg",
			["images/projects/3d perspectives/original/Japan.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/kw01 (Small).jpg",
			["images/projects/3d perspectives/original/kw01 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/kw02 (Small).jpg",
			["images/projects/3d perspectives/original/kw02 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/kw03 (Small).jpg",
			["images/projects/3d perspectives/original/kw03 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Lift.jpg",
			["images/projects/3d perspectives/original/Lift.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Lobby.jpg",
			["images/projects/3d perspectives/original/Lobby.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Radisson.jpg",
			["images/projects/3d perspectives/original/Radisson.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/residential01-big (Small).jpg",
			["images/projects/3d perspectives/original/residential01-big (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/residential02-big (Small).jpg",
			["images/projects/3d perspectives/original/residential02-big (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/residential03-big (Small).jpg",
			["images/projects/3d perspectives/original/residential03-big (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/retail02 (Small).jpg",
			["images/projects/3d perspectives/original/retail02 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/retail03 (Small).jpg",
			["images/projects/3d perspectives/original/retail03 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/retail04 (Small).jpg",
			["images/projects/3d perspectives/original/retail04 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/retail05 (Small).jpg",
			["images/projects/3d perspectives/original/retail05 (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/rock-big (Small).jpg",
			["images/projects/3d perspectives/original/rock-big (Small).jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/Rocks.jpg",
			["images/projects/3d perspectives/original/Rocks.jpg"]),
			new ArtWork("",
			"images/projects/3d perspectives/small03.jpg",
			["images/projects/3d perspectives/original/small03.jpg"])
		]
		this.categories.push(new Category("3D Perspectives", this.threeDArtWorks));
	}

	initRetailArtWorks(){
		this.retailArtWorks = [
			new ArtWork("1 Ton - Chatswood",
			"images/projects/retail/1 Ton - Chatswood/cover photo/cover.JPG",
			["images/projects/retail/1 Ton - Chatswood/1 Ton - Chatswood Interchange (Small).JPG",
			"images/projects/retail/1 Ton - Chatswood/1 Ton - Chatswood Interchange 02 (Small).JPG",
			"images/projects/retail/1 Ton - Chatswood/1 Ton - Chatswood Interchange03 (Small).JPG",
			"images/projects/retail/1 Ton - Chatswood/1 Ton - Chatswood Interchange04 (Small).JPG"]),
			new ArtWork("Bread Top",
			"images/projects/retail/Bread Top/cover photo/cover.JPG",
			["images/projects/retail/Bread Top/Bread Top 01 (Small).JPG",
			"images/projects/retail/Bread Top/Bread Top02 (Small).JPG"]),
			new ArtWork("Centre Cuts",
			"images/projects/retail/Centre Cuts/cover photo/cover.JPG",
			["images/projects/retail/Centre Cuts/Centre Cuts - Centre Park (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park 09 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park02 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park03 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park04 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park05 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park06 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park07 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park08 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park10 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park11 (Small).JPG",
			"images/projects/retail/Centre Cuts/Centre Cuts - Centre Park12 (Small).JPG"]),
			new ArtWork("Coffee Fest",
			"images/projects/retail/Coffee Fest/cover photo/cover.JPG",
			["images/projects/retail/Coffee Fest/Coffee Fest - MQ (Small).JPG"]),
			new ArtWork("Coffee Shop",
			"images/projects/retail/Coffee Shop/cover photo/cover.JPG",
			["images/projects/retail/Coffee Shop/Coffee Shop - St Ives Village (2) (Small).JPG",
			"images/projects/retail/Coffee Shop/Coffee Shop - St Ives Village (Small).JPG"]),
			new ArtWork("Fish CO",
			"images/projects/retail/Fish CO/cover photo/cover.JPG",
			["images/projects/retail/Fish CO/IMG_4481 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4482 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4483 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4484 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4485 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4486 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4487 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4488 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4489 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4490 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4491 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4492 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4493 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4494 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4495 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4496 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4497 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4498 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4499 (Small).JPG",
			"images/projects/retail/Fish CO/IMG_4500 (Small).JPG"]),
			new ArtWork("Free Choices",
			"images/projects/retail/Free Choices/cover photo/cover.JPG",
			["images/projects/retail/Free Choices/Freechoice - Chatswood Interchange (2) (Small).JPG",
			"images/projects/retail/Free Choices/Freechoice - Chatswood Interchange (Small).JPG"]),
			new ArtWork("Master Yang",
			"images/projects/retail/Master Yang/cover photo/cover.JPG",
			["images/projects/retail/Master Yang/Master Yang - Chatswood Interchange (Small).JPG"]),
			new ArtWork("Mio",
			"images/projects/retail/Mio/cover photo/Mio (Small).jpg",
			["images/projects/retail/Mio/Mio (Small).jpg"]),
			new ArtWork("My Donut Box",
			"images/projects/retail/My Donut Box/cover photo/cover.JPG",
			["images/projects/retail/My Donut Box/IMG_4407 (Small).JPG",
			"images/projects/retail/My Donut Box/IMG_4408 (Small).JPG"]),
			new ArtWork("Shinobu",
			"images/projects/retail/Shinobu/cover photo/cover.JPG",
			["images/projects/retail/Shinobu/Shinobu (Small).JPG"]),
			new ArtWork("Sheo Box",
			"images/projects/retail/Shoe Box/cover photo/cover.JPG",
			["images/projects/retail/Shoe Box/Shoe Box - Miranda Westfield (Small).JPG",
			"images/projects/retail/Shoe Box/Shoe Box - Miranda Westfield 02 (Small).JPG",
			"images/projects/retail/Shoe Box/Shoe Box - Miranda Westfield 03 (Small).JPG",
			"images/projects/retail/Shoe Box/Shoe Box - Miranda Westfield 04 (Small).JPG"]),
			new ArtWork("Sushi World",
			"images/projects/retail/Sushi World/cover photo/cover.JPG",
			["images/projects/retail/Sushi World/Sushi - MQ (Small).JPG"]),
			new ArtWork("The Depot Nail Bar",
			"images/projects/retail/The Depot Nail Bar/cover photo/cover.JPG",
			["images/projects/retail/The Depot Nail Bar/IMG_4456 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4457 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4459 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4465 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4466 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4467 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4468 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4469 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4471 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4473 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4474 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4475 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4476 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4479 (Small).JPG",
			"images/projects/retail/The Depot Nail Bar/IMG_4480 (Small).JPG"]),
			new ArtWork("The Living Room",
			"images/projects/retail/The Living Room/cover photo/cover.JPG",
			["images/projects/retail/The Living Room/The Living Room (Small).JPG",
			"images/projects/retail/The Living Room/The Living Room - St Ives Village (2) (Small).JPG",
			"images/projects/retail/The Living Room/The Living Room - St Ives Village (Small).JPG",
			"images/projects/retail/The Living Room/The Living Room - St Ives Village 03 (Small).JPG",
			"images/projects/retail/The Living Room/The Living Room - St Ives Village 04 (Small).JPG",
			"images/projects/retail/The Living Room/The Living Room 02 (Small).JPG"]),
			new ArtWork("Tong Li Supermarket",
			"images/projects/retail/Tong Li Supermarket/cover photo/cover.jpg",
			["images/projects/retail/Tong Li Supermarket/20160923_165221 (Small).jpg",
			"images/projects/retail/Tong Li Supermarket/20160923_165240 (Small).jpg",
			"images/projects/retail/Tong Li Supermarket/20160923_165306 (Small).jpg",
			"images/projects/retail/Tong Li Supermarket/Tong Li - Hurstville (2) (Small).JPG",
			"images/projects/retail/Tong Li Supermarket/Tong Li - Hurstville (Small).JPG",
			"images/projects/retail/Tong Li Supermarket/Tong Li - Hurstville 03 (Small).JPG"]),
			new ArtWork("VNH Dollars",
			"images/projects/retail/VNH Dollars/cover photo/cover.JPG",
			["images/projects/retail/VNH Dollars/VNH Dollars (Small).JPG"]),
			new ArtWork("Voi",
			"images/projects/retail/Voi/cover photo/cover.JPG",
			["images/projects/retail/Voi/VOI - Centre Park (Small).JPG"])
		];
		this.categories.push(new Category("Retail", this.retailArtWorks));
	}
}